language: c
sudo: required

services:
  - docker

env:
  - PLATFORM=esp8266
  - PLATFORM=esp32
  - PLATFORM=cc3200
  - PLATFORM=cc3220

install: curl -fsSL https://mongoose-os.com/downloads/mos/install.sh | /bin/bash
script: ~/.mos/bin/mos build --local --verbose --platform $PLATFORM
